name: Benchmarks
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call:

jobs:
  benchmarks:
    name: Benchmarks
    uses: apple/swift-nio/.github/workflows/benchmarks.yml@main
    with:
      benchmark_package_path: Benchmarks
