name: Benchmarks

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call:

jobs:
  benchmarks:
    name: Benchmarks
    # Workaround https://github.com/nektos/act/issues/1875
    uses: apple/swift-nio/.github/workflows/benchmarks.yml@main
    with:
      benchmark_package_path: Benchmarks
