name: Issue Comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  update-benchmarks:
    if: github.event.issue.pull_request && contains(fromJson('["COLLABORATOR","MEMBER","OWNER"]'), github.event.issue.author_association) && startsWith(github.event.comment.body, '/action update benchmarks')
    name: Update Benchmarks
    # Workaround https://github.com/nektos/act/issues/1875
    uses: rnro/swift-nio/.github/workflows/benchmarks_update.yml@main
    with:
      benchmark_package_path: "Benchmarks"
      issue_url: ${{ github.event.comment.issue_url }}

  rerun-benchmarks:
    name: Benchmarks
    needs: update-benchmarks
    uses: ./.github/workflows/benchmarks.yml
